apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask
  namespace: ecommerce
  labels:
    app: ecommerce
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ecommerce
      tier: backend
  template:
    metadata:
      labels:
        app: ecommerce
        tier: backend
    spec:
      containers:
      - name: flask-backend
        image: tiangolo/uwsgi-nginx-flask:python3.8
        env:
        - name: FLASK_ENV
          valueFrom:
            configMapKeyRef:
              name: flask-config
              key: FLASK_ENV
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: flask-secret
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: flask-secret
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: flask-secret
              key: MYSQL_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: flask-secret
              key: MYSQL_DATABASE
        ports:
        - containerPort: 80